
//interface de las acciones
export interface Action {
    type: string,
    payload?: any
}

//Los tipos de las acciones
export const NEW_ACCOUNT = 'NEW_ACCOUNT';
export const NEW_LOGIN = 'NEW_LOGIN';
export const NEWS_ACTION = 'NEWS_ACTION';
export const NEW_ACTION = 'NEW_ACTION';
export const VIDEOGAMES_ACTION = 'VIDEOGAMES_ACTION';
export const VIDEOGAME_ACTION = 'VIDEOGAME_ACTION';
export const SESSION_ACTION = 'SESSION_ACTION';
export const NEW_COMMENT = 'NEW_COMMENT';
export const VALORACIONES_ACTION = 'VALORACIONES_ACTION';
export const OBTAIN_USER_DATA_ACTION = 'OBTAIN_USER_DATA_ACTION';
export const GENRES_ACTION = 'GENRES_ACTION';
export const GENRE_ACTION = 'GENRE_ACTION';
export const PUBLISHERS_ACTION = 'PUBLISHERS_ACTION';
export const PUBLISHER_ACTION = 'PUBLISHER_ACTION';
export const WEBS_ACTION = 'WEBS_ACTION';
export const CHANGE_USER_IMAGE_ACTION = 'CHANGE_USER_IMAGE_ACTION';
export const CHANGE_COMMENTS_ACTION = 'CHANGE_COMMENTS_ACTION';
export const VACIAR_REDUCER_VIDEOJUEGO = 'VACIAR_REDUCER_VIDEOJUEGO';
export const VACIAR_REDUCER_VIDEOJUEGOS = 'VACIAR_REDUCER_VIDEOJUEGOS';
export const VACIAR_REDUCER_NOTICIA = 'VACIAR_REDUCER_NOTICIA';
export const VACIAR_REDUCER_NOTICIAS = 'VACIAR_REDUCER_NOTICIAS';
export const VACIAR_REDUCER_REGISTRO = 'VACIAR_REDUCER_REGISTRO';
export const JUEGOS_FAVORITOS_MODIFICADOS = 'JUEGOS_FAVORITOS_MODIFICADOS';
export const WEBS_FAVORITAS_MODIFICADAS = "WEBS_FAVORITAS_MODIFICADAS";
export const VACIAR_REDUCER_GENRE = 'VACIAR_REDUCER_GENRE';
export const VACIAR_REDUCER_EDITOR = 'VACIAR_REDUCER_EDITOR';